---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insureme-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insureme-app
  template:
    metadata:
      labels: 
        app: insureme-app
    spec:
      containers:
        - name: insureme-app
          image: mahithareddy/insureme:1.0
          ports: 
          - containerPort: 8081
          env:
            - name: PORT
              value: "8081"

---
apiVersion: v1
kind: Service
metadata:
  name: insureme-app-service
spec:
  selector:
    app: insureme-app
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      nodePort: 30084
  type: NodePort
  
